package sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SampleDTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SampleDTO() {
    }

}